development:
    sessions:
        default:
            hosts:
                -   localhost:27017
            database: svconverter
    options:
        include_type_for_serialization: true
        preload_models:
            - video
            - usuario
        scope_overwrite_exception: true
        raise_not_found_error: false



production:
    sessions:
        default:
            hosts: 
                -   ds053218.mongolab.com:53218
            database: heroku_app19299671
            username: svconverteruser
            password: svconverter
    options:
        include_type_for_serialization: true
        preload_models:
            - video
            - usuario
        scope_overwrite_exception: true
        raise_not_found_error: false